# Practica 4 
Medidas de distancia y similitud

* **Objetivo** -> Aplicar, comparar e interpretar diferentes medidas de distancia y similitud: distancia Euclidiana, distancia Manhattan, similitud del coseno, similitud de Jaccard y distancia de Hamming

* **Instrucciones generales** -> Resuelve cada una de las secciones de la práctica. En los ejercicios que lo soliciten, realiza primero los cálculos manualmente y posteriormente comprueba los resultados utilizando Python.
No basta con presentar únicamente el resultado numérico. En cada ejercicio deberás explicar brevemente qué significa el resultado obtenido

<hr />

## Parte 1. Distancia Euclidiana y Manhattan
Se cuenta con la informacion de 5 usuarios


| Usuario | Edad | Horas de estudio por semana | Cursos terminados |
| :--- | :---: | :---: | :---: |
| **A** | 22 | 12 | 4 |
| **B** | 25 | 10 | 5 |
| **C** | 38 | 5 | 2 |
| **D** | 24 | 15 | 6 |
| **E** | 29 | 8 | 4 |

* Considera a cada usuario como un vector formado por las tres caracteristicas anteriores. Calcula manualmente la distancia euclidiana entre los siguientes pares:

* A y B
* A y C
* A y D

* Calcula manualmente la distancia Manhattan entre los mismos pares.

In [2]:
import pandas as pd
import numpy as np

def distancia_euclidiana(punto1, punto2):
    return sum((x - y) ** 2 for x, y in zip(punto1, punto2)) ** 0.5

def distancia_manhattan(punto1, punto2):
    return sum(abs(x - y) for x, y in zip(punto1, punto2))

## Variables 
A = [22, 12, 4]
B = [25, 10, 5]
C = [38, 5, 2]
D = [24, 15, 6]
E = [29, 8, 4] 

## Dis Euclidianas
dist_euclidianas = {
    'B': distancia_euclidiana(A, B),
    'C': distancia_euclidiana(A, C),
    'D': distancia_euclidiana(A, D)
}

punto_sim_eucl = min(dist_euclidianas, key=dist_euclidianas.get)
mas_sim_Euclidiana = dist_euclidianas[punto_sim_eucl]

## Dis Manhattan
dist_manhattan = {
    'B': distancia_manhattan(A, B),
    'C': distancia_manhattan(A, C),
    'D': distancia_manhattan(A, D)
}

punto_sim_manh = min(dist_manhattan, key=dist_manhattan.get)
mas_sim_manhattan = dist_manhattan[punto_sim_manh]

print('='*40)
print('El punto más similar a A según la distancia:')
print(f'Euclidiana: Punto {punto_sim_eucl} con una distancia de {mas_sim_Euclidiana:.4f}')
print(f'Manhattan:  Punto {punto_sim_manh} con una distancia de {mas_sim_manhattan}')
print('='*40)

========================================
El punto más similar a A según la distancia:
Euclidiana: Punto B con una distancia de 3.7417
Manhattan:  Punto B con una distancia de 6
========================================

### Resultados
1. Indica si ambas medidas producen la misma conclusion
* Si, ambas producen la misma conclusion, sin embargo, el resultado numerico difiere un poco debido a la formula en que cada una usa para calcular la distancia

2. Analiza cuál de las tres características parece tener mayor influencia sobre las distancias obtenidas
* La caracteristica con la mayoe influencia es edad, debido a que presenta los numeros mas grandes, si quitamos esa variable, el resultado diferira considerablemente del de ahora, por otro lado, si borramos Cursos terminados, no se vera muy afectado el resultado

3. Explica si consideras conveniente realizar un escalamiento de los datos antes de calcular las distancias
* Si, es muy conveniente escalar los datos, de esta forma, todas las variables se encontrarian en el mismo rango de valores y aportarian una cantidad de informacion similar entre ellas. Retomando el ejemplo anterior. Despues de escalar las variables, si quitaramos la columna de edad, tendria el mismo peso a quitar la columna Cursos terminados

<hr />


## Parte 2. Matrices de distancia
Utilizando Python y los cinco usuarios de la sección anterior:Construye una matriz de distancia Euclidiana de 5 × 5.Construye una matriz de distancia Manhattan de 5 × 5.Presenta ambas matrices utilizando nombres de filas y columnas correspondientes a los usuarios A, B, C, D y E.Identifica el par de usuarios más parecido en cada matriz. Posteriormente, identifica el par de usuarios más diferente en cada matriz

In [ ]:
personas = [A, B, C, D, E]
n = len(personas)

euclidiana = [[0.0 for _ in range(n)] for _ in range(n)]
manhattiana = [[0.0 for _ in range(n)] for _ in range(n)]

for i in range(n):
    for j in range(n):
        euclidiana[i][j] = round(distancia_euclidiana(personas[i], personas[j]), 2)

for i in range(n):
    for j in range(n):
        manhattiana[i][j] = distancia_manhattan(personas[i], personas[j])

nombres = ['A','B','C','D','E']

m1 = pd.DataFrame(euclidiana, columns=nombres, index=nombres)
m2 = pd.DataFrame(manhattiana,columns=nombres, index=nombres)

matriz_sin_diagonal = m1.where(np.eye(len(m1)) == 0)
dist_min = matriz_sin_diagonal.min().min()
par_min = matriz_sin_diagonal.stack().idxmin()


dist_max = m1.max().max()
par_max = m1.stack().idxmax()


print('='*40)
print('Matriz euclidiana' )
print(f'Usuarios mas similares: {par_min[0]} y {par_min[1]} (Distancia: {dist_min})')
print(f'Usuarios mas diferentes: {par_max[0]} y {par_max[1]} (Distancia: {dist_max})')
print('='*40)

m1

========================================
                         Matriz euclidiana
Usuarios mas similares (Euclidiana): A y B (Distancia: 3.74)
Usuarios mas diferentes (Euclidiana): C y D (Distancia: 17.66)
========================================

       A      B      C      D     E
A   0.00   3.74  17.58   4.12  8.06
B   3.74   0.00  14.25   5.20  4.58
C  17.58  14.25   0.00  17.66  9.70
D   4.12   5.20  17.66   0.00  8.83
E   8.06   4.58   9.70   8.83  0.00

In [16]:
matriz_manhattan_sin_diag = m2.where(np.eye(len(m2)) == 0)
dist_min_m2 = matriz_manhattan_sin_diag.min().min()
par_min_m2 = matriz_manhattan_sin_diag.stack().idxmin()

# 2. Para la distancia máxima
dist_max_m2 = m2.max().max()
par_max_m2 = m2.stack().idxmax()

# --- IMPRESIÓN DE RESULTADOS ---
print('='*40)
print('Matriz manhattan' )
print(f'Usuarios más similares: {par_min_m2[0]} y {par_min_m2[1]} (Distancia: {dist_min_m2})')
print(f'Usuarios más diferentes: {par_max_m2[0]} y {par_max_m2[1]} (Distancia: {dist_max_m2})')
print('='*40)
m2

========================================
Matriz manhattan
Usuarios más similares: A y B (Distancia: 6.0)
Usuarios más diferentes: C y D (Distancia: 28)
========================================

    A   B   C   D   E
A   0   6  25   7  11
B   6   0  21   7   7
C  25  21   0  28  14
D   7   7  28   0  14
E  11   7  14  14   0