# Pokemon dataset
This dataset contains information on all 802 Pokemon from all Seven Generations of Pokemon. The information contained in this dataset include Base Stats, Performance against Other Types, Height, Weight, Classification, Egg Steps, Experience Points, Abilities, etc. The information was scraped from http://serebii.net/
<hr />

In [1]:
import pandas as pd

master = pd.read_csv('./data/pokemon.csv')

In [ ]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), str(7)
memory usage: 256.7 KB

In [4]:
missing = {
    'Numero de faltantes: ': master.isna().sum(),
    'Porcentaje de faltantes: ': master.isna().mean()
}
print('='*40)
print(missing)
print('='*40)

========================================
{'Numero de faltantes: ': abilities              0
against_bug            0
against_dark           0
against_dragon         0
against_electric       0
against_fairy          0
against_fight          0
against_fire           0
against_flying         0
against_ghost          0
against_grass          0
against_ground         0
against_ice            0
against_normal         0
against_poison         0
against_psychic        0
against_rock           0
against_steel          0
against_water          0
attack                 0
base_egg_steps         0
base_happiness         0
base_total             0
capture_rate           0
classfication          0
defense                0
experience_growth      0
height_m              20
hp                     0
japanese_name          0
name                   0
percentage_male       98
pokedex_number         0
sp_attack              0
sp_defense             0
speed                  0
type1                  0
type2                384
weight_kg             20
generation             0
is_legendary           0
dtype: int64, 'Porcentaje de faltantes: ': abilities            0.000000
against_bug          0.000000
against_dark         0.000000
against_dragon       0.000000
against_electric     0.000000
against_fairy        0.000000
against_fight        0.000000
against_fire         0.000000
against_flying       0.000000
against_ghost        0.000000
against_grass        0.000000
against_ground       0.000000
against_ice          0.000000
against_normal       0.000000
against_poison       0.000000
against_psychic      0.000000
against_rock         0.000000
against_steel        0.000000
against_water        0.000000
attack               0.000000
base_egg_steps       0.000000
base_happiness       0.000000
base_total           0.000000
capture_rate         0.000000
classfication        0.000000
defense              0.000000
experience_growth    0.000000
height_m             0.024969
hp                   0.000000
japanese_name        0.000000
name                 0.000000
percentage_male      0.122347
pokedex_number       0.000000
sp_attack            0.000000
sp_defense           0.000000
speed                0.000000
type1                0.000000
type2                0.479401
weight_kg            0.024969
generation           0.000000
is_legendary         0.000000
dtype: float64}
========================================

In [5]:
master.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [6]:
master[['percentage_male','type2','height_m']].describe()

       percentage_male    height_m
count       703.000000  781.000000
mean         55.155761    1.163892
std          20.261623    1.080326
min           0.000000    0.100000
25%          50.000000    0.600000
50%          50.000000    1.000000
75%          50.000000    1.500000
max         100.000000   14.500000

In [7]:
master['type2'].nunique()

18

Debido a la presencia de algunos valores nulos, se opto por hacer ciertas imputaciones, entre ellas se hicieron:
1. **percentage_male** -> Debido a la alra desviacion estandar y la similitud entre los 3 cuartiles y que la media es parecida a la mediana, se toma la mediana para imputar.
2. **height_m** -> Aqui se observa una baja desviacion estandar, por lo que se toma la media para imputar
3. **type2** -> Solamente se cambiara el valor 'NaN' por un No, haciendo referencia a que notiene segundo tipo el pokemon

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

x = master.drop(columns=['is_legendary'])
y = master['is_legendary']

preprossesor = ColumnTransformer